import { Size } from 'fancy-canvas';
import { IDestroyable } from '../helpers/idestroyable';
import { ISubscription } from '../helpers/isubscription';
import { IHorzScaleBehavior } from '../model/ihorz-scale-behavior';
import { InvalidationLevel } from '../model/invalidate-mask';
import { ChartWidget } from './chart-widget';
import { MouseEventHandlers, MouseEventHandlerTouchEvent, TouchMouseEvent } from './mouse-event-handler';
import { PriceAxisStub } from './price-axis-stub';
export declare class TimeAxisWidget<HorzScaleItem> implements MouseEventHandlers, IDestroyable {
    private readonly _chart;
    private readonly _options;
    private readonly _element;
    private readonly _leftStubCell;
    private readonly _rightStubCell;
    private readonly _cell;
    private readonly _dv;
    private readonly _canvasBinding;
    private readonly _topCanvasBinding;
    private _leftStub;
    private _rightStub;
    private readonly _mouseEventHandler;
    private _rendererOptions;
    private _mouseDown;
    private _size;
    private readonly _sizeChanged;
    private readonly _widthCache;
    private _isSettingSize;
    private readonly _horzScaleBehavior;
    constructor(chartWidget: ChartWidget<HorzScaleItem>, horzScaleBehavior: IHorzScaleBehavior<HorzScaleItem>);
    destroy(): void;
    getElement(): HTMLElement;
    leftStub(): PriceAxisStub | null;
    rightStub(): PriceAxisStub | null;
    mouseDownEvent(event: TouchMouseEvent): void;
    touchStartEvent(event: MouseEventHandlerTouchEvent): void;
    mouseDownOutsideEvent(): void;
    pressedMouseMoveEvent(event: TouchMouseEvent): void;
    touchMoveEvent(event: MouseEventHandlerTouchEvent): void;
    mouseUpEvent(): void;
    touchEndEvent(): void;
    mouseDoubleClickEvent(): void;
    doubleTapEvent(): void;
    mouseEnterEvent(): void;
    mouseLeaveEvent(): void;
    getSize(): Size;
    sizeChanged(): ISubscription<Size>;
    setSizes(timeAxisSize: Size, leftStubWidth: number, rightStubWidth: number): void;
    optimalHeight(): number;
    update(): void;
    getBitmapSize(): Size;
    drawBitmap(ctx: CanvasRenderingContext2D, x: number, y: number): void;
    paint(type: InvalidationLevel): void;
    private _drawAdditionalSources;
    private _drawBackground;
    private _drawBorder;
    private _drawTickMarks;
    private _alignTickMarkLabelCoordinate;
    private _drawLabels;
    private _lineColor;
    private _textColor;
    private _fontSize;
    private _baseFont;
    private _baseBoldFont;
    private _getRendererOptions;
    private _setCursor;
    private _recreateStubs;
    private readonly _canvasSuggestedBitmapSizeChangedHandler;
    private readonly _topCanvasSuggestedBitmapSizeChangedHandler;
}
